version: '3'
services:
  myapp:
    container_name: myapp
    restart: always
    build: .
    ports:
      - '80:3000'
    networks:
      - redis
    depends_on:
      - redis
  redis:
    image: redis:latest
    restart: always 
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
      - redis
networks:
  redis:
    driver: bridge


